// src/pages/ProjectVisualizer.jsx

import React, { useState, useEffect, useCallback } from "react";
import { useNodesState, useEdgesState, addEdge } from "@xyflow/react";
import * as babelParser from "@babel/parser";
import traverse from "@babel/traverse";
import * as babelTypes from "@babel/types";
import * as csstree from "css-tree";
import path from "path-browserify";
import { Link } from "react-router-dom"; // <-- ADD THIS
import { Home } from "lucide-react"; // <-- ADD THIS

// --- Component Imports ---
import LoadingScreen from "@/components/LoadingScreen";
import ReadmeModal from "@/components/ReadmeModal";
import FileExplorer from "@/components/FileExplorer";
import CodeEditor from "@/components/CodeEditor";
import Visualizer from "@/components/Visualizer";
import { Button } from "@/components/ui/button"; // <-- ADD THIS
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";

// --- Hook Imports ---
import { useDebounce } from "@/hooks/useDebounce";

// --- Util Imports (NOW INCLUDES WALKERS) ---
import {
  processDirectory,
  resolveImportPath,
  buildFileTree,
  generateFeatureBullets,
  walkDOM, // <-- IMPORTED FROM UTILS
  walkBabelAST, // <-- IMPORTED FROM UTILS
} from "@/utils";

// --- CSS Imports ---
import "@xyflow/react/dist/style.css";

function ProjectVisualizer() {
  // --- STATE MANAGEMENT ---
  const [projectFiles, setProjectFiles] = useState([]);
  const [activeFileContent, setActiveFileContent] = useState(
    '// Click "Open Folder" to start'
  );

  // State for live project editing
  const [activeFilePath, setActiveFilePath] = useState(null);
  const debouncedContent = useDebounce(activeFileContent, 500);
  const [graphableFiles, setGraphableFiles] = useState([]);

  // State for UI
  const [showReadme, setShowReadme] = useState(false);
  const [readmeContent, setReadmeContent] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [editorLanguage, setEditorLanguage] = useState("javascript");

  // State for React Flow
  const [nodes, setNodes, onNodesChange] = useNodesState([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState([]);
  const onConnect = useCallback(
    (params) => setEdges((eds) => addEdge(params, eds)),
    [setEdges]
  );

  // --- LOGIC HANDLERS ---
  // ... (handleFolderOpen, handleFileClick, handleGenerateReadme are UNCHANGED) ...
  const handleFolderOpen = async () => {
    try {
      setIsLoading(true);
      const directoryHandle = await window.showDirectoryPicker();
      const allFiles = await processDirectory(directoryHandle);
      setProjectFiles(allFiles);
      const entryFile = allFiles.find(
        (f) => f.path.endsWith("index.js") || f.path.endsWith("App.js")
      );
      let fileToOpen;
      if (entryFile) fileToOpen = entryFile;
      else if (allFiles.length > 0) fileToOpen = allFiles[0];
      if (fileToOpen) {
        setActiveFileContent(fileToOpen.content);
        setActiveFilePath(fileToOpen.path);
        if (fileToOpen.path.endsWith(".css")) setEditorLanguage("css");
        else if (fileToOpen.path.endsWith(".html")) setEditorLanguage("html");
        else setEditorLanguage("javascript");
      }
      setIsLoading(false);
    } catch (err) {
      console.error("Error opening folder (or user cancelled):", err);
      setIsLoading(false);
    }
  };

  const handleFileClick = (file) => {
    setActiveFileContent(file.content);
    setActiveFilePath(file.path);
    if (file.path.endsWith(".css")) setEditorLanguage("css");
    else if (file.path.endsWith(".html")) setEditorLanguage("html");
    else setEditorLanguage("javascript");
  };

  const handleGenerateReadme = () => {
    // We don't need to parse package.json anymore since we only want the tree

    // 1. Build the file tree string
    const fileTree = buildFileTree(projectFiles);

    // 2. Create the simple Markdown content
    const mdContent = `
# Project Structure

\`\`\`
${fileTree}
\`\`\`

---
*Generated by CodeFlow IDE*
`;
    setReadmeContent(mdContent);
    setShowReadme(true);
  };

  // --- CORE LOGIC (EFFECTS) ---

  // ... (EFFECT 1, 2, 3 are UNCHANGED) ...
  useEffect(() => {
    setGraphableFiles(projectFiles);
  }, [projectFiles]);

  useEffect(() => {
    if (activeFilePath) {
      setGraphableFiles((currentFiles) =>
        currentFiles.map((file) =>
          file.path === activeFilePath
            ? { ...file, content: debouncedContent }
            : file
        )
      );
    }
  }, [debouncedContent, activeFilePath]);

  useEffect(() => {
    if (graphableFiles.length === 0) {
      setNodes([]);
      setEdges([]);
      return;
    }
    const allFilePaths = graphableFiles.map((f) => f.path);
    const newNodes = [];
    const newEdges = [];
    graphableFiles.forEach((file, i) => {
      newNodes.push({
        id: file.path,
        data: { label: path.basename(file.path) },
        position: { x: (i % 5) * 200, y: Math.floor(i / 5) * 100 },
      });
    });
    graphableFiles.forEach((file) => {
      if (!/\.(js|jsx|ts|tsx)$/.test(file.path)) return;
      try {
        const ast = babelParser.parse(file.content, {
          sourceType: "module",
          plugins: ["jsx", "typescript"],
          errorRecovery: true,
        });
        traverse(ast, {
          ImportDeclaration({ node }) {
            const importPath = node.source.value;
            const resolvedPath = resolveImportPath(
              file.path,
              importPath,
              allFilePaths
            );
            if (resolvedPath && allFilePaths.includes(resolvedPath)) {
              newEdges.push({
                id: `e-${file.path}-to-${resolvedPath}`,
                source: resolvedPath,
                target: file.path,
                animated: true,
              });
            } else if (resolvedPath) {
              if (!newNodes.find((n) => n.id === resolvedPath)) {
                newNodes.push({
                  id: resolvedPath,
                  data: { label: resolvedPath },
                  position: {
                    x: Math.random() * 500,
                    y: Math.random() * 500 + 400,
                  },
                  style: { background: "#fdd", borderColor: "#f00" },
                });
              }
              newEdges.push({
                id: `e-${file.path}-to-${resolvedPath}`,
                source: resolvedPath,
                target: file.path,
                label: "external",
              });
            }
          },
        });
      } catch (err) {
        console.error(`Could not parse ${file.path}: ${err.message}`);
      }
    });
    setNodes(newNodes);
    setEdges(newEdges);
  }, [graphableFiles, setNodes, setEdges]);

  // --- EFFECT 4 (Scratchpad) IS NOW REMOVED ---
  // Its logic will be moved to LiveCodePage.jsx

  // --- RENDER (JSX) ---
  return (
    <div className="h-screen w-screen bg-background text-foreground">
      {isLoading && <LoadingScreen />}

      {showReadme && (
        <ReadmeModal
          content={readmeContent}
          onClose={() => setShowReadme(false)}
        />
      )}

      <ResizablePanelGroup direction="horizontal" className="h-full w-full">
        {/* Panel 1: File Explorer */}
        <ResizablePanel defaultSize={20} minSize={15}>
          {/* --- ADDED A WRAPPER DIV --- */}
          <div className="p-2 flex flex-col h-full min-h-0">
            <Button asChild variant="outline" size="sm" className="mb-2">
              <Link to="/">
                <Home className="mr-2 h-4 w-4" /> Back to Home
              </Link>
            </Button>
            <FileExplorer
              projectFiles={projectFiles}
              onFolderOpen={handleFolderOpen}
              onReadmeGen={handleGenerateReadme}
              onFileClick={handleFileClick}
              isDisabled={projectFiles.length === 0}
            />
          </div>
        </ResizablePanel>

        <ResizableHandle withHandle />

        <ResizablePanel defaultSize={40} minSize={30}>
          <CodeEditor
            content={activeFileContent}
            onContentChange={setActiveFileContent}
            path={activeFilePath}
            language={editorLanguage}
          />
        </ResizablePanel>

        <ResizableHandle withHandle />

        <ResizablePanel defaultSize={40} minSize={30}>
          <Visualizer
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
          />
        </ResizablePanel>
      </ResizablePanelGroup>
    </div>
  );
}

export default ProjectVisualizer;
